version: "2.1"
services:
  database:
    container_name: biopark_postgres
    image: postgres
    ports: ["5432:5432"]
    volumes: ["pg-data:/var/lib/postgresql"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: building_biopark
volumes:
  pg-data:
